# Generated by Django 5.0.2 on 2024-03-05 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_category_type_alter_category_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="limit",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 4, 19, 4, 46, 209043, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
