# Generated by Django 5.0.2 on 2024-03-07 19:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_user_is_staff_alter_limit_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="limit",
            name="end_date",
        ),
    ]
