# Generated by Django 5.0.2 on 2024-03-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_limit_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="limit",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
