# Generated by Django 5.0.2 on 2024-03-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_limit_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
