# Generated by Django 5.0.2 on 2024-05-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_transaction_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="limit",
            name="current_amount",
            field=models.IntegerField(default=0),
        ),
    ]
