# Generated by Django 5.0.2 on 2024-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_insert_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
