# Generated by Django 5.0.2 on 2024-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_category_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="category/"),
        ),
    ]
