from django.urls import path

from app.views import (
    RegistrationView,
    AuthView,
    AddTransactionView,
    TransactionListView,
    delete_transaction_view,
    edit_transaction_view,
    edit_target_view,
    delete_target_view,
    edit_limit_view,
    delete_limit_view,
    welcome_view,
    UserView,
    CreateTargetView,
    CreateLimitView,
    TargetListView,
    LimitView,
    GenerateChartData,
    DownloadExcelView,
    MainView,
    GoogleView,
    get_target_by_id_view,
    get_transaction_by_id_view,
    get_categories_targets,
    TelegramAuthLinkView,
    LogoutView,
)

urlpatterns = [
    path("", MainView.as_view(), name="main"),
    path("welcome/", welcome_view, name="welcome"),
    path("registration/", RegistrationView.as_view(), name="registration"),
    path("auth/", AuthView.as_view(), name="auth"),
    path("user", UserView.as_view(), name="user"),
    path("add_transaction/", AddTransactionView.as_view(), name="add_transaction"),
    path("transactions/", TransactionListView.as_view(), name="transactions"),
    path(
        "edit_transaction/<int:transaction_id>/",
        edit_transaction_view,
        name="edit_transaction",
    ),
    path(
        "delete_transaction/<int:transaction_id>/",
        delete_transaction_view,
        name="delete_transaction",
    ),
    path(
        "get_categories_targets/",
        get_categories_targets,
        name="get_categories_targets",
    ),
    path(
        "transaction_id/<int:transaction_id>/",
        get_transaction_by_id_view,
        name="get_transaction_by_id",
    ),
    path("create_target/", CreateTargetView.as_view(), name="create_target"),
    path("target/", TargetListView.as_view(), name="target"),
    path(
        "edit_target/<int:target_id>/",
        edit_target_view,
        name="edit_target",
    ),
    path(
        "delete_target/<int:target_id>/",
        delete_target_view,
        name="delete_target",
    ),
    path("target_id/<int:target_id>/", get_target_by_id_view, name="get_target_by_id"),
    path("limit/", LimitView.as_view(), name="limit"),
    path("create_limit/", CreateLimitView.as_view(), name="create_limit"),
    path(
        "edit_limit/<int:limit_id>/",
        edit_limit_view,
        name="edit_limit",
    ),
    path(
        "delete_limit/<int:limit_id>/",
        delete_limit_view,
        name="delete_limit",
    ),
    path(
        "chart/<str:transaction_type>/",
        GenerateChartData.as_view(),
        name="generate_chart_data",
    ),
    path("download_excel/", DownloadExcelView.as_view(), name="download_excel"),
    path("google/", GoogleView.as_view(), name="google_login"),
    path(
        "telegram/auth/start/",
        TelegramAuthLinkView.as_view(),
        name="telegram_auth_link",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
]
